CREATE TABLE Users(
UserID int NOT NULL AUTO_INCREMENT,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
Address VARCHAR(255) NOT NULL,
City VARCHAR(255) NOT NULL,
PRIMARY key(UserID)
);

INSERT INTO Students VALUES("Jane Doe","57 Union St","Glasgow","G13RB","Scotland");
